version: "3.8"

services:
  localstack:
    image: localstack/localstack
    container_name: oms-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,dynamodb,sqs
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack:/var/lib/localstack"
