server:
  port: ":8082"
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 70s
  name: "oms_service"

service:
  name: "oms_service"

mongo:
  uri: "mongodb://localhost:27017"
  dbname: "OMS"
  collectionName: "orders"

s3:
 bucketName: "oms-temp-public"
 fileName: "orders.csv"

# aws:
#   region: "${AWS_REGION:-us-east-1}"
#   account: "${AWS_ACCOUNT_ID:-000000000000}"
#   endpoint: "${AWS_ENDPOINT_URL:-http://localhost:4566}"
#   accessKeyId: "${AWS_ACCESS_KEY_ID:-test}"
#   secretAccessKey: "${AWS_SECRET_ACCESS_KEY:-test}"
#   sqsendpoint: "${AWS_ENDPOINT_URL_SQS:-http://localhost:4566}"
#   sqsname: "${AWS_SQS_NAME:-sqs-queue}"

aws:
  region: "us-east-1"
  account: "000000000000"
  accessKeyId: "test"
  secretAccessKey: "test"
  sqsendpoint: "http://localhost:4566"
  sqsname: "sqs-queue"

client:
  serviceName: "ims-service"
  baseURL: "http://localhost:8080"
  maxIdleConns: 100
  maxIdleConnsPerHost: 100

http:
  timeout: 30s

consumer:
  numberOfWorker: 1
  concurrencyPerWorker: 1
  maxMessagesCount: 10
  visibilityTimeout: 30   # in seconds
  isAsync: false
  sendBatchMessage: false