server:
  port: ":8082"

service:
  name: "oms_service"

mongo:
  uri: "mongodb://localhost:27017"
  dbname: "OMS"
  collectionName: "orders"

s3:
 bucketName: "oms-test-bucket"
 fileName: "orders.csv"

aws:
  region: "${AWS_REGION:-us-east-1}"
  account: "${AWS_ACCOUNT_ID:-000000000000}"
  endpoint: "${AWS_ENDPOINT_URL:-http://localhost:4566}"
  accessKeyId: "${AWS_ACCESS_KEY_ID:-test}"
  secretAccessKey: "${AWS_SECRET_ACCESS_KEY:-test}"
  sqsendpoint: "${AWS_ENDPOINT_URL_SQS:-http://localhost:4566}"

# aws:
#   region: "us-east-1"
#   account: "000000000000"
#   endpoint: "http://localhost:4566"
#   accessKeyId: "test"
#   secretAccessKey: "test"
#   sqsendpoint: "http://localhost:4566"

